#!/bin/sh

echo "==========================="
echo "Running SuccessScript"
echo "==========================="

if [ $XCS_INTEGRATION_RESULT == "succeeded" ] ; then
    echo "Congratulations on another successful integration!"
  ~/BotConfig/uploadToTestFlight 
fi

