#!/bin/sh

echo "==========================="
echo "Running SuccessScript"
echo "==========================="

if [ $XCS_INTEGRATION_RESULT == "succeeded" ] ; then
    echo "Uploading to Testflight following successful integration"
  ~/BotConfig/uploadToTestFlight $1 
fi

