#!/bin/sh

echo "==========================================="
echo "Post-Integration Warnings and Issues Script for ${BOT_BRANCH}"
echo "==========================================="
echo ""


if [ $XCS_ERROR_COUNT -eq 0 ] && [ $XCS_TEST_FAILURE_COUNT -eq 0 ]; then

echo "Uploading to Testflight from Warnings and Issues script"
~/BotConfig/uploadToTestFlight 

else

echo "Cannot upload archive because of build errors or test failures"

fi
